name: greeting-using-shell-commands
on: push
env:
  Greeting_Object: "morning"
jobs:
  greeting:
    runs-on: ubuntu-latest
    env:
      Name: "toney"
    steps:
      - env: 
          Greet: "Hi"
        run: echo "$Greet $Name good $Greeting_Object"
